# -*- coding: utf-8 -*-
"""data_cleaning_exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bhWmbn72TNhsjuZnW8huKeVqYlqotjA
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import os

from google.colab import files
uploaded = files.upload()

# Create an empty list to collect each stock's DataFrame
dataframes = []

# Loop through all uploaded files
for filename in uploaded.keys():
    df = pd.read_csv(filename)
    if 'date' in df.columns:
        ticker = filename.split('_')[0]
        df['name'] = ticker
        df['date'] = pd.to_datetime(df['date'], errors='coerce')  # Safe conversion
        dataframes.append(df)
    else:
        print(f"Skipping {filename} — no 'Date' column.")
    # Extract the ticker from the filename (e.g., "AAPL_data.csv" -> "AAPL")
    ticker = filename.split('_')[0]
    df['name'] = ticker  # Add a column for the stock name/ticker

    dataframes.append(df)

# Combine all DataFrames into one
combined_df = pd.concat(dataframes, ignore_index=True)

# Optional: Convert the 'Date' column to datetime
combined_df['date'] = pd.to_datetime(combined_df['date'])

# Preview
print(combined_df.head())
print(combined_df.info())

combined_df = combined_df.drop_duplicates(subset=['date', 'name'])

# Now calculate the daily returns
combined_df['daily_return'] = combined_df.groupby('name')['close'].pct_change()

# Pivot the data again
returns_df = combined_df.pivot(index='date', columns='name', values='daily_return')

# Drop rows with missing values
returns_df = returns_df.dropna()

# Calculate the correlation matrix
correlation_matrix = returns_df.corr()

# Preview the correlation matrix
print(correlation_matrix.head())